# Generated by Django 3.2.7 on 2021-10-01 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(default=datetime.datetime(2021, 10, 2, 0, 1, 46, 201454))),
            ],
        ),
    ]
